### ISSUE TITLE
Use screenshots of Firefox, not of Chrome, at addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [google/service-worker-detector#10]
From <https://addons.mozilla.org/addon/service-worker-detector/>, updated 2018-04-20: 

![image](https://user-images.githubusercontent.com/192271/40281656-7e6d1944-5c5c-11e8-9400-e2935d345470.png)

![image](https://user-images.githubusercontent.com/192271/40281670-9d422ff8-5c5c-11e8-8e7d-33db36736c6e.png)

Shots of the extension in its various states – in a Firefox window, with the [page action](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction) menu dropped down, where appropriate – will help new users to know what to expect; the scope of the extension.

Ideally, one of the shots should zoom in on the page action icon in its non-clicked state. So that (lazy) readers don't have to click the shot to appreciate the detail. 

Thanks :-)

**Comment by tomayac** [comment]
Thanks for the report. I have just submitted Firefox screenshots, please see the [extension overview page](https://addons.mozilla.org/en-US/firefox/addon/service-worker-detector/).

**Comment by grahamperrin** [comment]
👍 thanks. 

Pointing at a construction worker icon alone, in Waterfox: 

![2018-05-25 14 07 43](https://user-images.githubusercontent.com/192271/40547980-4c5fb3d0-602b-11e8-8bf1-80f2919a9927.png)

![2018-05-25 14 07 43 more cropped](https://user-images.githubusercontent.com/192271/40548076-96c08094-602b-11e8-8b8f-b48b6544e96d.png)

If you'd like me to take a shot of something similar in Firefox, when I'm next there, just say.
