### ISSUE TITLE
Document non-appearance of the icon

### ISSUE THREAD

**Issue by grahamperrin** [google/service-worker-detector#12]
https://github.com/google/service-worker-detector/issues/7#issuecomment-330342723 for example and more recently, <https://addons.mozilla.org/addon/service-worker-detector/reviews/1161836/>: 

> … Just installed this addon but it did not detect that Youtube installed a service worker. …

<https://github.com/google/service-worker-detector/issues/9#issuecomment-391673085>: 

… the extension only triggers when `navigator.serviceWorker.controller` is no longer `null`, _i.e._, as soon as the service worker becomes active ([documentation](https://developer.mozilla.org/docs/Web/API/ServiceWorkerContainer/controller)).

### Suggestions

Update https://github.com/google/service-worker-detector/blob/master/README.md with a short simple explanation of why the icon does not appear in some situations. The opening paragraph is probably ideal, a handful of bullet points should suffice. 

Add _About this extension_ information to https://addons.mozilla.org/addon/service-worker-detector/ – include a link to `README.md` but people _love_ to not follow links to documentation ;-/ so FWIW I reckon it's worth including a brief explanation, re: non-appearance of the icon, at the AMO page itself. 

----

AFAICT (from [The Air Horner](https://airhorner.com/) example): 

- expect no Service Worker Detector icon after the initial load of a page
- expect the icon to appear after a simple reload; if a tab is closed then reopened; if a tab is loaded after restoring a session. 

From some of the earlier issues I gather that in some cases, a first simple reload might not suffice, two reloads are necessary. True? 

In some cases the worker will be active following a hard refresh e.g. <kbd>Shift</kbd>-reload or <kbd>Control</kbd>-<kbd>F5</kbd>. This seems to be true for The Air Horner. 

In other cases the worker will **not** be active following a hard refresh. This seems to be true for the current worker for Gmail – scope https://mail.google.com/mail/u/0/

### Side note

Mozilla bug [1495275 - Corrupted Content Error for gmail](https://bugzilla.mozilla.org/show_bug.cgi?id=1495275) (I'm using Service Worker Detector, with Waterfox, in connection with this bug).

**Comment by grahamperrin** [comment]
> … In other cases the worker will **not** be active following a hard refresh. This seems to be true for the current worker for Gmail …

Hmm, I just found the opposite. Contradicting myself. Given Mozilla bug 1495275, maybe Gmail is not a good example … sorry …

**Comment by tomayac** [comment]
Thanks, @grahamperrin!
