### ISSUE TITLE
[Firefox] does not work on twitter

### ISSUE THREAD

**Issue by ghost** [google/service-worker-detector#13]
Because of Firefox CSP issue. You are trying to inject inline script and Twitter blocks them.

>Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). contentscript.js:50:20

**Comment by tomayac** [comment]
I tried the following: 

- Setting a `nonce` for the injected script:
  https://github.com/google/service-worker-detector/blob/463d2b38ee024d591901775d73f90b54e63cb186/contentscript.js#L29

  https://github.com/google/service-worker-detector/blob/463d2b38ee024d591901775d73f90b54e63cb186/contentscript.js#L45-L50

- I then repeat this `nonce` in the extension's manifest:
  https://github.com/google/service-worker-detector/blob/463d2b38ee024d591901775d73f90b54e63cb186/manifest.json#L8

This works fine on a page like Airhorner.com, but still fails on Twitter.com. Maybe I'm holding CSP wrong, no expert here, but definitely help wanted…

**Comment by tomayac** [comment]
FWIW, this is less strict on Chrome: https://developer.chrome.com/extensions/contentSecurityPolicy#interactions.

**Comment by tomayac** [comment]
Looks like this is https://bugzilla.mozilla.org/show_bug.cgi?id=1267027. 
(via https://twitter.com/digitarald/status/1191386042034556930)

**Comment by tomayac** [comment]
After looking into it more, it seems indeed related to https://bugzilla.mozilla.org/show_bug.cgi?id=1267027 (thanks @digitarald for the pointer).

**Comment by tomayac** [comment]
I think this is a "won't fix", sorry. It looks like Twitter is really trying hard to make sure no injected scripts run on their platform. I don't have the energy right now to work on this.

**Comment by tomayac** [comment]
The related [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) is still open. So maybe Firefox will fix this, I don't think I can do much as an extension author at this point.
