### ISSUE TITLE
Doesn't detect on Outlook?

### ISSUE THREAD

**Issue by ericlaw1979** [google/service-worker-detector#7]
outlook.live.com/mail uses a ServiceWorker (as seen in the DevTools Application tab) but doesn't light up the detector icon?

**Comment by tomayac** [comment]
Have you reloaded the page at least twice? Soft-reloaded that is, as a hard-reload won’t work. On mobile now, can’t test myself.

**Comment by ericlaw1979** [comment]
Ah. Reloading the page again made it appear. I guess that's expected?

**Comment by tomayac** [comment]
Yes, the Service Worker will only be active upon repeat visits. Working as intended :-D
