### ISSUE TITLE
No Indicator on Firefox

### ISSUE THREAD

**Issue by pascalheidmann** [google/service-worker-detector#8]
On Firefox no indicator/app icon is added to the toolbar. Also there isn't one added to the "customize" menu so you can't even add it later.
Not sure if this is directly an issue of the extension or firefox not completely copying chrome...

**Comment by tomayac** [comment]
Same as https://github.com/google/service-worker-detector/issues/7?

**Comment by pascalheidmann** [comment]
@tomaya nope, the indicator is completely absent in firefox. I'm on the beta channel.

**Comment by tomayac** [comment]
Thanks, need to investigate tomorrow, I’m away from my desk right now.

**Comment by tomayac** [comment]
Duh, believe it or not, my Mac wouldn’t boot today and I am working on a Chromebook now where Firefox isn’t an option. I hope to look into this soon once IT re-images my machine. ```¯\_(ツ)_/¯```

**Comment by tomayac** [comment]
I think this is working fine. See the screenshot for details. Did you soft-reload twice? I'm on Firefox 55.0.3 (64-bit). I am closing the Issue for now, please comment if you still hit this and I am happy to investigate further.

<img width="1087" alt="firefox" src="https://user-images.githubusercontent.com/145676/30639343-bc7f7802-9dfe-11e7-9041-4893cee63f71.png">
